### ISSUE TITLE
Overlay Picture doesn't work

### ISSUE THREAD

**Issue by msenya25** [Woyken/pixelplanet.fun-OverlayPicture#1]

**Comment by Woyken** [comment]
I have noticed that.
Recent update has changed a lot of things internally... 
Working on update.

**Comment by Woyken** [comment]
Should be fixed now.
Check for updates if it doesn't fix itself and it should work.
![image](https://user-images.githubusercontent.com/13166802/73119906-bc85e500-3f70-11ea-914a-86b4260f847d.png)

**Comment by msenya25** [comment]
ok
