### ISSUE TITLE
How can acess bot?

### ISSUE THREAD

**Issue by phoniks2k** [Woyken/pixelplanet.fun-OverlayPicture#2]
The map request "unlock code"

**Comment by Woyken** [comment]
As the tooltip on "Enable bot" checkbox says. I don't feel like it's ready yet. I'm slowly working on it... The unlock code currently is used only by people who help me "beta test" it

**Comment by phoniks2k** [comment]
Ok, thx man

Em sáb, 2 de mai de 2020 06:27, Karolis Užkuraitis <notifications@github.com>
escreveu:
