### ISSUE TITLE
overlay bot

### ISSUE THREAD

**Issue by idclelelda3etrasdf34** [Woyken/pixelplanet.fun-OverlayPicture#21]
at some point there was this lil wheelchair icon with a more or less functional "bot", but it's gone. any way to get it back?

**Comment by Woyken** [comment]
Yeah... About that one... 
With recent major rewrite, I changed a lot of internal stuff and ended up removing the bot, it was really "hacky" solution. 
I'll add it back at some point, but that will take some time to rewrite

**Comment by idclelelda3etrasdf34** [comment]
Aw ok, thx for the answer. I did like and could use the feature quite well, despite it being a lil clunky at times. Looking forward to seeing it back, should time and motivation allow
