### ISSUE TITLE
Script is open but will not lay image 

### ISSUE THREAD

**Issue by pixelfun138** [Woyken/pixelplanet.fun-OverlayPicture#3]
Started happening 3 days ago. The script opens up on pixel planet but will no longer load the image.

**Comment by Woyken** [comment]
Can you look at the console? Any errors there?

**Comment by pixelfun138** [comment]
I'm going to be 100% honest, Im a total boomer when it comes to scripts and coding, I just wanted to let you know. PNG's just seem to not be loading up. Not sure if they changed something within the site.

**Comment by pixelfun138** [comment]
Ok so yesterday the 18th of june 20. It was working a for a bit. Now I load it up and the image that you are overlaying in pixel planet is staying stuck in the right hand corner of the screen as you scroll through the map. Like I said, I don't really know much about scripts and such but I hope this helps. Seems like its something they are doing to interfere.

**Comment by Woyken** [comment]
Closing this issue.
By now, it was changed a couple of times how overlay is reading PNG files. Previously 3rd party library was used, caused some issues. Ended up using browser's native solution (don't know why I didn't start with it), more image types should be supported now.
