### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by DjsProject** [Woyken/pixelplanet.fun-OverlayPicture#35]
button with overlay disappeared

**Comment by Thugsisreallybadlol** [comment]
yea

**Comment by Woyken** [comment]
Oh no, looks like they don't allow cross origin requests anymore. Current script depended on that.
Hopefully nothing else changed... 
I'll try to make a fix later today.

**Comment by bababoyy** [comment]
I have made a temproarily patch to CORS block. https://www.toptal.com/developers/hastebin/raw/pudoxuleyo.user.js

**Comment by Woyken** [comment]
For the time being I updated script, just added whole script to userscript itself.
Check for script updates in userscript manager (tampermonkey)
