### ISSUE TITLE
Some stuff

### ISSUE THREAD

**Issue by pixelplanetdev** [Woyken/pixelplanet.fun-OverlayPicture#4]
Now that i don't use outdated hammerjs anymore, tracking the mouse coordinates for userscripts is a bit shitty. And there will probably be changes in the feature to it.
What would you prefer to make it less hacky?

I could i.e. just make the site send the current coords to some window.coordsUpdate(x, y) function that you could overwrite.
If receiving the chunks is an issue, i could make the same there too, and just send them to some window.receivedChunk(chunk) function that you can overwrite.

**Comment by Woyken** [comment]
Thanks for notifying, 
Actually, if you are willing to make something like that, it would be great.

Maybe some object for extensions would be cleaner a bit. Just an idea, less pollution directly on window. 
Something like window.pixelPlanetExtensions.onCoordsChanged()

Thanks again 😁

**Comment by pixelplanetdev** [comment]
What's needed of the chunks?
Do you replace or modify something in them, or do you just need them as UInt8Array?

**Comment by Woyken** [comment]
All I would need is it's ID and UInt8Array would do just fine. All I do is try to keep same state along side you

**Comment by pixelplanetdev** [comment]
ok, i will think about something

**Comment by Woyken** [comment]
Thanks!

**Comment by pixelplanetdev** [comment]
I made it as an EventEmitter on window.pixelPlanetEvents.
Those would be the events that i added on it:
https://github.com/pixelplanetdev/pixelplanet/blob/production/src/store/extensions.js
`
window.pixelPlanetEvents.addListener('sethover', (hover) => {
  console.log(hover)
});
`
like this would print the mouse coordinates in the console

The 'receivechunk' event gives the ChunkRGB object, and all chunks, so also the zooming tiles, 3D and historical view. You would have to filter the ones you need, like `if (chunk.isBasechunk)` would be just the 2D chunks on the closest zoom level. They don't have an UInt8Array of the color indexes, but the image as a canvas element on chunk.image.
If you just need the color index of a specific pixel, there's a chunk.getColorIndex([x, y]) method.
Or do you really need the UInt8Array?

**Comment by Woyken** [comment]
That's not necessary, I can just read it from the chunk.image myself.
This is great.

Just another thing that would be useful is SET_SCALE hook, zoom tracking is quite hacky too

**Comment by pixelplanetdev** [comment]
Sure, added it.
But this scale isn't the same as the actual scale used on the site, it doesn't clamp
```viewscale = (scale > 0.85 && scale < 1.20) ? 1.0 : scale;```
is the actual scale.

i removed center from receivechunk, it's redundant because that's in chunk.cell anyway.

I also removed pixelupdate, i don't really want that there
