### ISSUE TITLE
The template is not deleted 

### ISSUE THREAD

**Issue by WitiaUA** [Woyken/pixelplanet.fun-OverlayPicture#48]
Hello, I cannot delete the template after the recent update of the script (it seems that it has been deleted, I refresh the page, it is there again)

https://user-images.githubusercontent.com/108870328/177808633-1f508200-eb0d-4b90-914d-da3e45f084c6.mp4

**Comment by Woyken** [comment]
Should be fixed now. Check for Userscript updates
