### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Asmund11** [Woyken/pixelplanet.fun-OverlayPicture#5]
Can you add some designation for pixels i need to click? Because when i restore picture it's hard to see what pixels should i click sometimes (even with transparency 0-100%). If you'll have time, can you add some red cross or something that will be more visible on needed pixels?
![image](https://user-images.githubusercontent.com/29029324/102021907-fa0f7e80-3d8b-11eb-8183-07bf4acdd171.png)

**Comment by Woyken** [comment]
Feature was added a little while ago called "smol pixels" it makes 1/3 size pixels with empty space in between, so it looks like little dots in all the places you need to click.
I think this can be closed
