### ISSUE TITLE
Script not linked to https://fuckyouarkeros.fun

### ISSUE THREAD

**Issue by Bakuretsue** [Woyken/pixelplanet.fun-OverlayPicture#54]
Hello, the script for tamper doesn't work on other pixelplanet domains. It does work for certain other scripts however.
![image](https://user-images.githubusercontent.com/46354836/188841459-6a298e1c-80b6-436d-8a7f-fbc47cae434e.png)

**Comment by Woyken** [comment]
Added the mirror link to userscript settings, in theory it should work
