### ISSUE TITLE
Doesnt work after the new update

### ISSUE THREAD

**Issue by FBSANAKONDA** [Woyken/pixelplanet.fun-OverlayPicture#89]
The new update added overlays as a feature, but I would still prefer the userscript because of provacy reasons, but it does not work, it glitches, the size is bad, etc. Please fix or answer.

**Comment by Woyken** [comment]
Well, they have removed all the hooks that I was using to update positions.
Updated it to use whatever is left, now it will snap back to position after you stop moving. It's jarring but for the time being, it's the best I can do

**Comment by FBSANAKONDA** [comment]
> Well, they have removed all the hooks that I was using to update positions. Updated it to use whatever is left, now it will snap back to position after you stop moving. It's jarring but for the time being, it's the best I can do

thank you

**Comment by Sallbet** [comment]
> Well, they have removed all the hooks that I was using to update positions. Updated it to use whatever is left, now it will snap back to position after you stop moving. It's jarring but for the time being, it's the best I can do

Now it's this
```js
window.pixelPlanetEvents.on('setviewcoordinates', console.log) 
window.pixelPlanetEvents.on('setscale', console.log) 
```

**Comment by Woyken** [comment]
Oh, right, I forgot about those, thanks

**Comment by ghost** [comment]
it seems to work now. thank you.
